### ISSUE TITLE
Create Swift Version

### ISSUE THREAD

**Issue by dehlen** [perfaram/PFAboutWindow#6]
Hello,

I really like your library thats why I created a Swift version of PFAboutWindow and added AutoLayout to the .xib. 

Repository link is here: https://github.com/T-Rex-Editor/TRexAboutWIndowController

**Comment by perfaram** [comment]
Thanks, VERY nice job ! 
What do you prefer : I put a link on my README, or I turn your repo into a branch of mine (e.g. the "swift" branch) ?  (I'll credit you in both cases)

**Comment by dehlen** [comment]
Wow thanks for the kind words. A link in your README would be super cool.

**Comment by perfaram** [comment]
Done (in commit 03653dc9f78bdd0076ee5419be7ef233bff23e4d)
And thanks again !
