### ISSUE TITLE
Improve graphics for `visitWebsiteButton`

### ISSUE THREAD

**Issue by SoneeJohn** [perfaram/PFAboutWindow#7]
When clicking on the `visitWebsiteButton` button there is a rectangle overlay around the app icon. 
Screenshot 
<img width="519" alt="screen shot 2016-01-12 at 9 09 53 am" src="https://cloud.githubusercontent.com/assets/4827301/12264363/b0d46b44-b90c-11e5-8c64-d5135fd94835.png">
There shouldn't be a overlay IMO.

**Comment by SoneeJohn** [comment]
With 3b287d3 the button will now look like this:
<img width="519" alt="screen shot 2016-01-12 at 9 15 58 am" src="https://cloud.githubusercontent.com/assets/4827301/12264670/abb6e504-b90e-11e5-9edc-757c8f54239a.png">
This is looks better than before, 3b287d3 closes this issue.

**Comment by perfaram** [comment]
Thanks !!
